import type { FestivalReview } from '@shared/domain/review.model';

export const FESTIVAL_REVIEWS: readonly FestivalReview[] = [
  // ── Bigsound Festival ────────────────────────────────────────────────────
  {
    id: 'bigsound-01',
    festivalSlug: 'bigsound',
    author: 'Marta G.',
    rating: 5,
    comment: 'Dos días increíbles. El sonido en ambos escenarios era perfecto y la organización no falló en ningún momento. Volveré seguro.',
    date: '2025-06-28',
    verified: true,
  },
  {
    id: 'bigsound-02',
    festivalSlug: 'bigsound',
    author: 'Jordi F.',
    rating: 4,
    comment: 'Muy buen cartel para ser un festival de fin de semana. Las colas en las barras mejoraron notablemente respecto al año anterior.',
    date: '2025-06-29',
    verified: true,
  },
  {
    id: 'bigsound-03',
    festivalSlug: 'bigsound',
    author: 'Laura P.',
    rating: 5,
    comment: 'El ambiente era eléctrico desde el primer momento. La zona de food trucks era diversa y con precios razonables para ser un festival.',
    date: '2025-06-27',
    verified: false,
  },
  {
    id: 'bigsound-04',
    festivalSlug: 'bigsound',
    author: 'Carlos M.',
    rating: 3,
    comment: 'El cartel estuvo bien, aunque esperaba más sorpresas. El acceso en transporte público fue un caos el primer día.',
    date: '2025-06-28',
    verified: true,
  },
  {
    id: 'bigsound-05',
    festivalSlug: 'bigsound',
    author: 'Ana R.',
    rating: 5,
    comment: 'Una producción visual impresionante. El escenario principal tenía una pantalla enorme y el espectáculo de luz fue de lo mejor que he visto.',
    date: '2025-06-30',
    verified: false,
  },
  {
    id: 'bigsound-06',
    festivalSlug: 'bigsound',
    author: 'Pablo S.',
    rating: 4,
    comment: 'Fui con amigos y nos lo pasamos genial. Los escenarios secundarios esconden auténticas joyas que merece la pena explorar.',
    date: '2025-06-29',
    verified: true,
  },
  {
    id: 'bigsound-07',
    festivalSlug: 'bigsound',
    author: 'Nuria V.',
    rating: 4,
    comment: 'Muy cómodo de llegar desde el centro de Valencia. Buen festival para iniciarse en el mundo de los festivales urbanos.',
    date: '2025-06-27',
    verified: false,
  },
  {
    id: 'bigsound-08',
    festivalSlug: 'bigsound',
    author: 'Sergio L.',
    rating: 2,
    comment: 'Me esperaba más. El sonido en el escenario pequeño dejó bastante que desear y el precio de las consumiciones era elevado.',
    date: '2025-06-28',
    verified: true,
  },
  {
    id: 'bigsound-09',
    festivalSlug: 'bigsound',
    author: 'Cristina O.',
    rating: 5,
    comment: 'El mejor festival del área de Valencia para los amantes del pop y el urbano. La atmósfera es diferente a cualquier otro evento.',
    date: '2025-06-30',
    verified: true,
  },
  {
    id: 'bigsound-10',
    festivalSlug: 'bigsound',
    author: 'David N.',
    rating: 4,
    comment: 'Organización impecable. Señalización clara, personal amable y los tiempos entre actuaciones bien gestionados. Se nota la experiencia.',
    date: '2025-06-29',
    verified: false,
  },

  // ── Latin Fest ────────────────────────────────────────────────────────────
  {
    id: 'latin-fest-01',
    festivalSlug: 'latin-fest',
    author: 'Valeria C.',
    rating: 5,
    comment: 'Una noche que no olvidaré. El ambiente latino es único, todo el mundo baila y la energía es contagiosa desde el primer minuto.',
    date: '2025-07-05',
    verified: true,
  },
  {
    id: 'latin-fest-02',
    festivalSlug: 'latin-fest',
    author: 'Miguel A.',
    rating: 4,
    comment: 'El cartel de este año estuvo muy sólido. Los artistas cumplieron con las expectativas y el recinto estaba muy bien acondicionado.',
    date: '2025-07-06',
    verified: true,
  },
  {
    id: 'latin-fest-03',
    festivalSlug: 'latin-fest',
    author: 'Isabella R.',
    rating: 5,
    comment: 'Vine desde Madrid solo para Latin Fest y mereció muchísimo la pena. El público valenciano sabe pasárselo bien como pocos.',
    date: '2025-07-05',
    verified: false,
  },
  {
    id: 'latin-fest-04',
    festivalSlug: 'latin-fest',
    author: 'Tomás B.',
    rating: 3,
    comment: 'Las entradas son algo caras para lo que ofrece. El recinto es bonito pero el aforo era demasiado y costaba moverse.',
    date: '2025-07-06',
    verified: true,
  },
  {
    id: 'latin-fest-05',
    festivalSlug: 'latin-fest',
    author: 'Sofía M.',
    rating: 5,
    comment: 'La producción del escenario era espectacular. Los efectos de luces y el sonido pusieron los pelos de punta. Repetiré seguro.',
    date: '2025-07-07',
    verified: true,
  },
  {
    id: 'latin-fest-06',
    festivalSlug: 'latin-fest',
    author: 'Andrés P.',
    rating: 4,
    comment: 'Festival perfecto para una noche con amigos. La mezcla de reggaeton, salsa y bachata crea un ambiente increíblemente festivo.',
    date: '2025-07-05',
    verified: false,
  },
  {
    id: 'latin-fest-07',
    festivalSlug: 'latin-fest',
    author: 'Lucía F.',
    rating: 4,
    comment: 'Los artistas locales de apertura fueron una sorpresa muy agradable. Ojalá les den más minutos en ediciones futuras.',
    date: '2025-07-06',
    verified: false,
  },
  {
    id: 'latin-fest-08',
    festivalSlug: 'latin-fest',
    author: 'Raúl D.',
    rating: 2,
    comment: 'La app de gestión de pulseras falló varias veces y tardamos media hora en entrar. El festival en sí estuvo bien, pero la tecnología falló.',
    date: '2025-07-05',
    verified: true,
  },
  {
    id: 'latin-fest-09',
    festivalSlug: 'latin-fest',
    author: 'Carmen H.',
    rating: 5,
    comment: 'Llevo tres años viniendo y cada edición supera a la anterior. El nivel del cartel sube y la experiencia mejora con cada año.',
    date: '2025-07-07',
    verified: true,
  },
  {
    id: 'latin-fest-10',
    festivalSlug: 'latin-fest',
    author: 'Ernesto G.',
    rating: 4,
    comment: 'La zona VIP merece la inversión: buenas vistas, sin empujones y servicio rápido. Perfecta para disfrutar sin agobios.',
    date: '2025-07-06',
    verified: false,
  },

  // ── Medusa Festival ───────────────────────────────────────────────────────
  {
    id: 'medusa-01',
    festivalSlug: 'medusa',
    author: 'Àlex T.',
    rating: 5,
    comment: 'Medusa es el festival más épico de España. Cinco días frente al mar con los mejores DJs del planeta. Una experiencia transformadora.',
    date: '2025-08-12',
    verified: true,
  },
  {
    id: 'medusa-02',
    festivalSlug: 'medusa',
    author: 'Elena K.',
    rating: 5,
    comment: 'La puesta en escena es de otro nivel. La pantalla gigante, los rayos láser sobre el mar... no hay palabras para describirlo.',
    date: '2025-08-13',
    verified: true,
  },
  {
    id: 'medusa-03',
    festivalSlug: 'medusa',
    author: 'Bruno L.',
    rating: 4,
    comment: 'Los escenarios secundarios son una auténtica joya. Encontré artistas emergentes que ahora escucho a diario. Gran curaduría musical.',
    date: '2025-08-11',
    verified: false,
  },
  {
    id: 'medusa-04',
    festivalSlug: 'medusa',
    author: 'Noa S.',
    rating: 3,
    comment: 'El festival es espectacular pero el transporte desde Valencia deja mucho que desear. Las lanzaderas se llenaban y tardaban horas.',
    date: '2025-08-14',
    verified: true,
  },
  {
    id: 'medusa-05',
    festivalSlug: 'medusa',
    author: 'Pau M.',
    rating: 5,
    comment: 'Amanecer bailando frente al Mediterráneo con el DJ set de cierre. Hay momentos en Medusa que son imposibles de olvidar.',
    date: '2025-08-12',
    verified: false,
  },
  {
    id: 'medusa-06',
    festivalSlug: 'medusa',
    author: 'Iria V.',
    rating: 4,
    comment: 'La zona de acampada estaba muy bien gestionada. Duchas suficientes, seguridad presente y un ambiente de comunidad muy especial.',
    date: '2025-08-15',
    verified: true,
  },
  {
    id: 'medusa-07',
    festivalSlug: 'medusa',
    author: 'Oscar R.',
    rating: 5,
    comment: 'El sonido del Main Stage es brutal. Se nota la inversión en equipos de audio. Cada bajo lo sientes en el pecho desde 200 metros.',
    date: '2025-08-13',
    verified: true,
  },
  {
    id: 'medusa-08',
    festivalSlug: 'medusa',
    author: 'Vera C.',
    rating: 2,
    comment: 'Los precios dentro del recinto son abusivos. Cuatro euros por una botella de agua cuando hace 35 grados no es aceptable.',
    date: '2025-08-11',
    verified: false,
  },
  {
    id: 'medusa-09',
    festivalSlug: 'medusa',
    author: 'Hugo P.',
    rating: 5,
    comment: 'Fui por primera vez y ya estoy pensando en el año que viene. La comunidad de Medusa es acogedora y el festival cuida cada detalle.',
    date: '2025-08-14',
    verified: true,
  },
  {
    id: 'medusa-10',
    festivalSlug: 'medusa',
    author: 'Laia F.',
    rating: 4,
    comment: 'Cinco días puede parecer mucho pero el tiempo vuela. Cada noche es diferente y la programación está pensada para que no te pierdas nada.',
    date: '2025-08-16',
    verified: false,
  },

  // ── Reggaeton Beach Festival ───────────────────────────────────────────────
  {
    id: 'rbf-01',
    festivalSlug: 'rbf',
    author: 'Daniela O.',
    rating: 5,
    comment: 'El Reggaeton Beach Festival es la fiesta del verano. Playa, sol y los mejores artistas del género. No podría pedir más.',
    date: '2025-07-05',
    verified: true,
  },
  {
    id: 'rbf-02',
    festivalSlug: 'rbf',
    author: 'Kevin S.',
    rating: 4,
    comment: 'La ubicación en Benidorm es perfecta. Combinar playa durante el día con el festival por la noche es el plan de verano ideal.',
    date: '2025-07-06',
    verified: false,
  },
  {
    id: 'rbf-03',
    festivalSlug: 'rbf',
    author: 'Priya N.',
    rating: 5,
    comment: 'El cartel fue top de principio a fin. Todos los artistas actuaron con energía máxima y el tiempo en escena fue generoso.',
    date: '2025-07-05',
    verified: true,
  },
  {
    id: 'rbf-04',
    festivalSlug: 'rbf',
    author: 'Marco R.',
    rating: 3,
    comment: 'El festival en sí es divertido pero el entorno de Benidorm puede resultar saturado en temporada alta. Mejor reservar hotel con antelación.',
    date: '2025-07-06',
    verified: true,
  },
  {
    id: 'rbf-05',
    festivalSlug: 'rbf',
    author: 'Juliana B.',
    rating: 5,
    comment: 'La atmósfera playera le da un toque único que no tienen otros festivales. Bailar descalza en la arena con música en directo es mágico.',
    date: '2025-07-07',
    verified: false,
  },
  {
    id: 'rbf-06',
    festivalSlug: 'rbf',
    author: 'Nicolás V.',
    rating: 4,
    comment: 'El público es jovial y el ambiente muy festivo. Si vas con el espíritu abierto, te lo pasarás increíblemente bien.',
    date: '2025-07-05',
    verified: true,
  },
  {
    id: 'rbf-07',
    festivalSlug: 'rbf',
    author: 'Camila T.',
    rating: 4,
    comment: 'Me sorprendió positivamente la variedad del cartel. No solo reggaeton: también hubo trap, salsa y urbano colombiano. Muy completo.',
    date: '2025-07-06',
    verified: false,
  },
  {
    id: 'rbf-08',
    festivalSlug: 'rbf',
    author: 'Roberto A.',
    rating: 2,
    comment: 'Las colas para entrar tardaron más de una hora. La gestión de accesos necesita mejorar urgentemente para ediciones futuras.',
    date: '2025-07-05',
    verified: true,
  },
  {
    id: 'rbf-09',
    festivalSlug: 'rbf',
    author: 'Vanessa L.',
    rating: 5,
    comment: 'Llevo cuatro años yendo al RBF y nunca me decepciona. Cada edición mejora en producción y el nivel del cartel es cada vez más alto.',
    date: '2025-07-07',
    verified: true,
  },
  {
    id: 'rbf-10',
    festivalSlug: 'rbf',
    author: 'Felipe C.',
    rating: 4,
    comment: 'El merchandising oficial tenía buena calidad este año. Los precios de las consumiciones eran razonables para el nivel del evento.',
    date: '2025-07-06',
    verified: false,
  },

  // ── Reve Festival ─────────────────────────────────────────────────────────
  {
    id: 'reve-01',
    festivalSlug: 'reve',
    author: 'Sandra M.',
    rating: 5,
    comment: 'Reve es sinónimo de espectáculo. El show visual superó todas mis expectativas y los artistas estuvieron en un nivel altísimo.',
    date: '2025-07-17',
    verified: true,
  },
  {
    id: 'reve-02',
    festivalSlug: 'reve',
    author: 'Nacho B.',
    rating: 4,
    comment: 'El recinto del Roig Arena es perfecto para este tipo de evento. La acústica es excelente y la visibilidad desde cualquier zona, buena.',
    date: '2025-07-17',
    verified: true,
  },
  {
    id: 'reve-03',
    festivalSlug: 'reve',
    author: 'Teresa F.',
    rating: 5,
    comment: 'Una noche única en Valencia. El cartel combinaba hits de pop con artistas más alternativos. Algo para cada gusto.',
    date: '2025-07-18',
    verified: false,
  },
  {
    id: 'reve-04',
    festivalSlug: 'reve',
    author: 'Alberto G.',
    rating: 3,
    comment: 'Las entradas son bastante caras para ser un evento de una sola noche. Aun así, la producción justificaba una buena parte del precio.',
    date: '2025-07-17',
    verified: true,
  },
  {
    id: 'reve-05',
    festivalSlug: 'reve',
    author: 'Patricia V.',
    rating: 5,
    comment: 'Fui con mi pareja y salimos encantados. El ambiente era elegante pero sin perder la diversión. Una propuesta diferente a lo habitual.',
    date: '2025-07-18',
    verified: false,
  },
  {
    id: 'reve-06',
    festivalSlug: 'reve',
    author: 'Dani C.',
    rating: 4,
    comment: 'El headliner fue lo más destacado de la noche. Actuación larga, generosa en hits y con un cierre emotivo que dejó al público en pie.',
    date: '2025-07-17',
    verified: true,
  },
  {
    id: 'reve-07',
    festivalSlug: 'reve',
    author: 'Rocío L.',
    rating: 4,
    comment: 'Gran experiencia para fans del pop español. La selección de artistas es cuidada y el evento transmite mucha profesionalidad.',
    date: '2025-07-18',
    verified: false,
  },
  {
    id: 'reve-08',
    festivalSlug: 'reve',
    author: 'Iván P.',
    rating: 2,
    comment: 'Me pilló lejos del escenario y la pantalla de la zona donde estaba no funcionaba bien. Para la próxima vez elegiré mejor la ubicación.',
    date: '2025-07-17',
    verified: true,
  },
  {
    id: 'reve-09',
    festivalSlug: 'reve',
    author: 'Begoña S.',
    rating: 5,
    comment: 'El mejor concierto-festival que he vivido en Valencia. La combinación de música y puesta en escena no tiene rival en la ciudad.',
    date: '2025-07-18',
    verified: true,
  },
  {
    id: 'reve-10',
    festivalSlug: 'reve',
    author: 'Toni A.',
    rating: 4,
    comment: 'Muy buena organización: acceso rápido, personal eficiente y el interior del recinto muy limpio en todo momento. Se nota el cuidado.',
    date: '2025-07-17',
    verified: false,
  },

  // ── Zevra Festival ────────────────────────────────────────────────────────
  {
    id: 'zevra-01',
    festivalSlug: 'zevra',
    author: 'Mireia T.',
    rating: 5,
    comment: 'Zevra tiene algo especial. El entorno de Cullera, el Mediterráneo de fondo y un cartel urbano de primer nivel. Perfección veraniega.',
    date: '2025-07-25',
    verified: true,
  },
  {
    id: 'zevra-02',
    festivalSlug: 'zevra',
    author: 'Àngel F.',
    rating: 4,
    comment: 'Cuatro días bien aprovechados. Cada jornada tiene personalidad propia y los artistas están muy bien seleccionados por estilos.',
    date: '2025-07-26',
    verified: false,
  },
  {
    id: 'zevra-03',
    festivalSlug: 'zevra',
    author: 'Leila A.',
    rating: 5,
    comment: 'El festival más bien organizado al que he ido. Entradas, accesos, seguridad, limpieza... todo funciona sin fisuras. Ejemplo a seguir.',
    date: '2025-07-27',
    verified: true,
  },
  {
    id: 'zevra-04',
    festivalSlug: 'zevra',
    author: 'Xavi P.',
    rating: 3,
    comment: 'El camping era básico y estaba bastante lejos del recinto. Si volviera, reservaría alojamiento en el pueblo en lugar de acampar.',
    date: '2025-07-25',
    verified: true,
  },
  {
    id: 'zevra-05',
    festivalSlug: 'zevra',
    author: 'Rita M.',
    rating: 5,
    comment: 'Vivir un amanecer frente al mar después de bailar toda la noche es algo que solo Zevra puede ofrecerte en la Comunitat Valenciana.',
    date: '2025-07-28',
    verified: false,
  },
  {
    id: 'zevra-06',
    festivalSlug: 'zevra',
    author: 'Carles V.',
    rating: 4,
    comment: 'El escenario secundario es un gran descubrimiento. Artistas locales con mucho talento que complementan perfectamente el cartel principal.',
    date: '2025-07-26',
    verified: true,
  },
  {
    id: 'zevra-07',
    festivalSlug: 'zevra',
    author: 'Neus B.',
    rating: 5,
    comment: 'El ambiente de Zevra es único. Es un festival que cuida al público: zonas de descanso, puntos de agua y personal siempre disponible.',
    date: '2025-07-27',
    verified: false,
  },
  {
    id: 'zevra-08',
    festivalSlug: 'zevra',
    author: 'Josep L.',
    rating: 3,
    comment: 'El headliner del último día canceló con poca antelación y la sustitución no estaba al mismo nivel. Decepción final en una edición que venía bien.',
    date: '2025-07-28',
    verified: true,
  },
  {
    id: 'zevra-09',
    festivalSlug: 'zevra',
    author: 'Alba C.',
    rating: 5,
    comment: 'Fui con un grupo grande y todos coincidimos: es el mejor festival de verano de la zona. La diversidad de estilos lo hace accesible para todos.',
    date: '2025-07-26',
    verified: true,
  },
  {
    id: 'zevra-10',
    festivalSlug: 'zevra',
    author: 'Marc R.',
    rating: 4,
    comment: 'La oferta gastronómica es de lo mejor que he visto en un festival español. Opciones veganas, locales y de calidad real. Un punto diferencial claro.',
    date: '2025-07-25',
    verified: false,
  },
];

/** Reviews indexed by festival slug for O(1) lookup. */
export const REVIEWS_BY_FESTIVAL: ReadonlyMap<string, readonly FestivalReview[]> = new Map(
  ['bigsound', 'latin-fest', 'medusa', 'rbf', 'reve', 'zevra'].map(slug => [
    slug,
    FESTIVAL_REVIEWS.filter(r => r.festivalSlug === slug),
  ]),
);
